
// This file has been generated by the GUI designer. Do not modify.
namespace AssetImporter.AddinItems
{
	public partial class AssetItemWidget
	{
		private global::Gtk.Table table1;

		private global::Gtk.FileChooserButton AssetPathChooser;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Image AssetPreviewImage;

		private global::Gtk.Label AssetResolutionLabel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget AssetImporter.AddinItems.AssetItemWidget
			global::Stetic.BinContainer.Attach(this);
			this.HeightRequest = 60;
			this.Name = "AssetImporter.AddinItems.AssetItemWidget";
			// Container child AssetImporter.AddinItems.AssetItemWidget.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table(((uint)(1)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.AssetPathChooser = new global::Gtk.FileChooserButton(global::Mono.Unix.Catalog.GetString("Select Asset File"), ((global::Gtk.FileChooserAction)(0)));
			this.AssetPathChooser.Name = "AssetPathChooser";
			this.table1.Add(this.AssetPathChooser);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.AssetPathChooser]));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(3));
			w1.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table1.Gtk.Table+TableChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.AssetPreviewImage = new global::Gtk.Image();
			this.AssetPreviewImage.WidthRequest = 50;
			this.AssetPreviewImage.HeightRequest = 50;
			this.AssetPreviewImage.Name = "AssetPreviewImage";
			this.vbox3.Add(this.AssetPreviewImage);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.AssetPreviewImage]));
			w2.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.AssetResolutionLabel = new global::Gtk.Label();
			this.AssetResolutionLabel.Name = "AssetResolutionLabel";
			this.vbox3.Add(this.AssetResolutionLabel);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.AssetResolutionLabel]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.table1.Add(this.vbox3);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox3]));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			this.Add(this.table1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
