
// This file has been generated by the GUI designer. Do not modify.
namespace AssetImporter.AddinItems
{
	public partial class AssetProjectExpandedWidget
	{
		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.VBox ProjectAssetVBox;

		private global::Gtk.Label ProjectNameLabel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget AssetImporter.AddinItems.AssetProjectExpandedWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "AssetImporter.AddinItems.AssetProjectExpandedWidget";
			// Container child AssetImporter.AddinItems.AssetProjectExpandedWidget.Gtk.Container+ContainerChild
			this.frame1 = new global::Gtk.Frame();
			this.frame1.Name = "frame1";
			this.frame1.BorderWidth = ((uint)(5));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.ProjectAssetVBox = new global::Gtk.VBox();
			this.ProjectAssetVBox.Name = "ProjectAssetVBox";
			this.ProjectAssetVBox.Spacing = 8;
			this.GtkAlignment.Add(this.ProjectAssetVBox);
			this.frame1.Add(this.GtkAlignment);
			this.ProjectNameLabel = new global::Gtk.Label();
			this.ProjectNameLabel.Name = "ProjectNameLabel";
			this.ProjectNameLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>GtkFrame</b>");
			this.ProjectNameLabel.UseMarkup = true;
			this.frame1.LabelWidget = this.ProjectNameLabel;
			this.Add(this.frame1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
		}
	}
}
